# Generated by Django 5.0.4 on 2024-04-03 21:44

import django.db.models.deletion
import solicitud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=100)),
                ('detalle_equipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('mantenimiento', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='En espera', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(default=solicitud.models.obtener_hora_actual)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
