# Generated by Django 5.0.4 on 2024-04-03 21:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=100)),
                ('servicio_solicitado', models.TextField()),
                ('servicio_realizado', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('tecnico', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(default=datetime.time(15, 44, 24, 838204))),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
