# Generated by Django 5.0.4 on 2024-04-03 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_alter_reporte_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(16, 7, 3, 108197)),
        ),
    ]
