# Generated by Django 5.0.4 on 2024-04-03 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_historial_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 58, 33, 113294)),
        ),
    ]
