# Generated by Django 5.0.4 on 2024-04-04 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_alter_historial_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 14, 29, 647028)),
        ),
    ]
