# Generated by Django 5.0.4 on 2024-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('n_serie', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=30)),
                ('diagnostico', models.TextField()),
                ('solucion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('en reparacion', 'en reparacion'), ('de vaja', 'de vaja')], max_length=20)),
            ],
        ),
    ]
